 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC SENSOR
 *
 * Author: Hazem Hisham
 *
 *******************************************************************************/

#include "gpio.h"
#include "ultrasonic.h"
#include "icu.h"
#include "util/delay.h"

static uint8 g_edgeCount=0;
static uint16 g_timeHigh=0;

/* Description:
 * function responsible for :
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the
 *  GPIO drive
 **/
void Ultrasonic_init(void){
	Icu_ConfigType Config={F_CPU_8,RISING};
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);
	Icu_init(&Config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
}
/*Description
*function responsible to  Send the Trigger pulse to the ultrasonic.*/
void Ultrasonic_Trigger(void){
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}
/*• Description
*Send the trigger pulse by using Ultrasonic_Trigger function.
* Start the measurements by the ICU from this moment.
* returns 	the measured distance in centimeter*/
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return (g_timeHigh / 58.8);
}
/* Description
* This is the call back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount==1){
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount==2){
		g_timeHigh=Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		g_edgeCount=0;
		Icu_setEdgeDetectionType(RISING);

	}
}
