 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ULTRASONIC SENSOR
 *
 * Author: Hazem Hisham
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

#define ULTRASONIC_TRIGGER_PORT 	PORTB_ID
#define ULTRASONIC_TRIGGER_PIN		PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/* Description:
 * function responsible for :
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the
 *  GPIO drive
 **/
void Ultrasonic_init(void);

/*Description
*function responsible to  Send the Trigger pulse to the ultrasonic.*/

void UltraSonic_Trigger(void);

/*• Description
*Send the trigger pulse by using Ultrasonic_Trigger function.
* Start the measurements by the ICU from this moment.
* returns 	the measured distance in centimeter*/
uint16 Ultrasonic_readDistance(void);
/* Description
* This is the call back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void);
#endif /* ULTRASONIC_H_ */
